ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
BOARD_TAG = mega2560
ARDUINO_LIBS = U8glib_Arduino
MONITOR_PORT =/dev/ttyUSB0
AVRDUDE_CONF = /etc/avrdude.conf

USER_LIB_PATH := $(realpath ../../)
include $(ARDMK_DIR)/Arduino.mk
